version: '3.8'

services:
  backend:
    container_name: fastapi
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    networks:
      - default
      
  frontend:
    container_name: vue
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./frontend:/app
    networks:
      - default

networks:
  default:
    driver: bridge